#include <LiquidCrystal.h>
LiquidCrystal lcd(13, 12, 11, 10, 9, 8);

// Definition of pin connection
const uint8_t coin_acceptor_pin=3;

// Decralation of usefull variables
int pulse=0;
long counter;
uint16_t coin_value;

String cutString(String str, int col) {
  return str.substring(0, col);
}

// Method to simplify printing in LCD
void lcdPrint(String str0, String str1){
  lcd.clear();  const int columns = 16;
  if (str0.length() > columns) str0 = cutString(str0, columns);
  if (str1.length() > columns) str1 = cutString(str1, columns);

  int pre_space0 = int((columns - str0.length()) / 2),
      pre_space1 = int((columns - str1.length()) / 2);

  lcd.setCursor(pre_space0, 0); lcd.print(str0);
  lcd.setCursor(pre_space1, 1); lcd.print(str1);
  
  delay(1e3);
}


// Method to count coin pulse generated by ISR
void countPulseISR(){
  Serial.println("Coin inserted");
  pulse++;
  counter = 0;
}

// Method to detect the value of coin enter coin acceptor module
uint8_t getCoin(){
  counter++;
  coin_value = 0;
  if(counter > 50){
    Serial.println("Counter: " + String(counter));
    if(pulse == 1) coin_value = 100;
    else if(pulse == 2) coin_value = 200;
    else if(pulse == 4) coin_value = 500;

    if(pulse > 0) Serial.println("Pulse: " + String(pulse));
    pulse = 0;
  }
  return coin_value;
}