#include "Interface.h"
#include "Control.h"

// Decralation of usefull variables
int service_cost, return_amount;
String services[] = {"Urination", "Defecation", "Shower"};

// Method to count coin pulse generated by ISR
void countPulseISR(){
  Serial.println("Coin inserted");
  pulse++;
  counter = 0;
}

// Method to provide change
void cashReturn(int amount){
  float i=0;
  if(amount >= 200){
    i = amount/200;
    while(i >= 1){
      servoRotate(servo2);
      delay(1e3);
      i -= 1;
    }
    if(i!=0) servoRotate(servo1);
  }else if(amount >= 100){
    i = amount/100;
    while(i>=1){
      servoRotate(servo1);
      delay(1e3);
      i -= 1;
    }  
  }
}

// Method to control the whole operation
void operation(){
  while(true){
    counter++;
    coin_value = 0;
    if(counter >= 30 && pulse >= 1){
      Serial.println("Counter: " + String(counter));
      if(pulse == 1) coin_value = 100;
      else if(pulse == 2) coin_value = 200;
      else if(pulse == 5) coin_value = 500;

      if(pulse > 0) Serial.println("Pulse: " + String(pulse));
      pulse = 0;
    }

    if(coin_value == 0)
      lcdPrint("Please", "Insert coin");
    else
      break;
  }

  Serial.println("Coin received successfull");
  lcdPrint("Amount received:", String(coin_value) + "Tsh."); delay(3e3);

  int i=0;
  while(!confirm){
    lcdPrint("Select service:", services[i]);
    if(digitalRead(btn2_pin) == LOW){
      delay(500);
      i++;
      if( i > 2 ) i = 0;
    }
  }

  // Assign the service cost
  if(i==0) service_cost=100;
  else if(i==1) service_cost=200;
  else if(i==2) service_cost=300;
  return_amount = coin_value - service_cost;

  if(service_cost > coin_value){
    lcdPrint("Sorry:", "Low balance");
    cashReturn(coin_value);
  }else{
    lcdPrint("Return amount:", String(return_amount) + "Tsh.");
    cashReturn(return_amount);
    digitalWrite(lock_pin, HIGH); 
    delay(2e3);
    digitalWrite(lock_pin, LOW);
    lcdPrint("SUCCESS", "...");
  }
  confirm = false;
}